apiVersion: v1
kind: ConfigMap
metadata:
  name: target-resource-config
data:
  config.yaml: |
    targetResouces:
    - apiVersion: v1
      resource:
        namespaced: true
        name: configmaps
      targetNamespace:
      - sample-ns
      - secure-ns
    - apiVersion: v1
      apiGroup: apps
      resource:
        namespaced: true
        name: deployments
      targetNamespace:
      - custom-ns
    - apiVersion: v1
      resource:
        namespaced: true
        name: services
      targetNamespace:
      - custom-ns
    keyConfigs:
    - keySecretName: akmebank-pub
      keySecretNamespace: custom-ns
    ignoreFields:
    - fields:
      - metadata.namespace
      objects:
      - kind: ClusterServiceVersion
    - fields:
      - metadata.managedFields.*
      - metadata.resourceVersion
      - metadata.selfLink
      - metadata.annotations.control-plane.alpha.kubernetes.io/leader
      - metadata.annotations.kubectl.kubernetes.io/last-applied-configuration
      - metadata.finalizers*
      - metadata.annotations.namespace
      - metadata.annotations.deprecated.daemonset.template.generation
      - metadata.creationTimestamp
      - metadata.uid
      - metadata.generation
      - status
      - metadata.annotations.cosign.sigstore.dev/imageRef
      objects:
      - name: '*'
    - fields:
      - secrets.*.name
      - imagePullSecrets.*.name
      objects:
      - kind: ServiceAccount
    - fields:
      - spec.ports.*.nodePort
      - spec.clusterIP
      - spec.clusterIPs.0
      objects:
      - kind: Service
    - fields:
      - metadata.labels.olm.api.*
      - metadata.labels.operators.coreos.com/*
      - metadata.annotations.*
      - spec.install.spec.deployments.*.spec.template.spec.containers.*.resources.limits.cpu
      - spec.cleanup.enabled
      objects:
      - kind: ClusterServiceVersion