// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	k8smanifest "github.com/yuji-watanabe-jp/k8s-manifest-sigstore/pkg/k8smanifest"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestIntegrityProfile) DeepCopyInto(out *ManifestIntegrityProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestIntegrityProfile.
func (in *ManifestIntegrityProfile) DeepCopy() *ManifestIntegrityProfile {
	if in == nil {
		return nil
	}
	out := new(ManifestIntegrityProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManifestIntegrityProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestIntegrityProfileList) DeepCopyInto(out *ManifestIntegrityProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManifestIntegrityProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestIntegrityProfileList.
func (in *ManifestIntegrityProfileList) DeepCopy() *ManifestIntegrityProfileList {
	if in == nil {
		return nil
	}
	out := new(ManifestIntegrityProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManifestIntegrityProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestIntegrityProfileSpec) DeepCopyInto(out *ManifestIntegrityProfileSpec) {
	*out = *in
	in.Match.DeepCopyInto(&out.Match)
	in.Parameters.DeepCopyInto(&out.Parameters)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestIntegrityProfileSpec.
func (in *ManifestIntegrityProfileSpec) DeepCopy() *ManifestIntegrityProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ManifestIntegrityProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestIntegrityProfileStatus) DeepCopyInto(out *ManifestIntegrityProfileStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestIntegrityProfileStatus.
func (in *ManifestIntegrityProfileStatus) DeepCopy() *ManifestIntegrityProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ManifestIntegrityProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchCondition.
func (in *MatchCondition) DeepCopy() *MatchCondition {
	if in == nil {
		return nil
	}
	out := new(MatchCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectUserBinding) DeepCopyInto(out *ObjectUserBinding) {
	*out = *in
	if in.Objects != nil {
		in, out := &in.Objects, &out.Objects
		*out = make(k8smanifest.ObjectReferenceList, len(*in))
		copy(*out, *in)
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectUserBinding.
func (in *ObjectUserBinding) DeepCopy() *ObjectUserBinding {
	if in == nil {
		return nil
	}
	out := new(ObjectUserBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ObjectUserBindingList) DeepCopyInto(out *ObjectUserBindingList) {
	{
		in := &in
		*out = make(ObjectUserBindingList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectUserBindingList.
func (in ObjectUserBindingList) DeepCopy() ObjectUserBindingList {
	if in == nil {
		return nil
	}
	out := new(ObjectUserBindingList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterObject.
func (in *ParameterObject) DeepCopy() *ParameterObject {
	if in == nil {
		return nil
	}
	out := new(ParameterObject)
	in.DeepCopyInto(out)
	return out
}
